### ISSUE TITLE
MOrgAna is not generating masks

### ISSUE THREAD

**Issue by EllenvdL** [LabTrivedi/MOrgAna#2]
I have installed morgana and trained the model succesfully. However, when I want to generate masks for all my images (converted to 8-bit tiff files) I get the following error:

`Loading C:/Users/ellle/Documents/20222023_internship/test_morgana/Cl.8\Snap-26462_72hdTAG11.tif ...
Predicting image...
Traceback (most recent call last):
  File "C:\Users\ellle\anaconda3\envs\morgana\lib\site-packages\morgana\GUIs\mainwindow.py", line 495, in predict
    mask_final = predict.make_watershed( mask_pred,
  File "C:\Users\ellle\anaconda3\envs\morgana\lib\site-packages\morgana\MLModel\predict.py", line 165, in make_watershed
    labels = segmentation.watershed(edge, markers)
  File "C:\Users\ellle\anaconda3\envs\morgana\lib\site-packages\skimage\segmentation\_watershed.py", line 215, in watershed
    _watershed_cy.watershed_raveled(image.ravel(),
  File "_watershed_cy.pyx", line 70, in skimage.segmentation._watershed_cy.__pyx_fused_cpdef
TypeError: No matching signature found`

I set up the environment with conda, python=3.9 and installed morgana=0.1.1. I got an error that pyQT5 was missing, so I installed pyqt with pip afterwards.

**Comment by grinic** [comment]
Hi @EllenvdL, what is the original type of your images? uint16?
Did you convert the images after training the model or did you train the model on 8-bit data?

**Comment by EllenvdL** [comment]
I trained the model on 8-bit data. The original images are 16-bit .czi files.

**Comment by grinic** [comment]
It looks like the error you report is due to scikit-image, see [here](https://stackoverflow.com/questions/52345236/sklearn-preprocessing-typeerror-no-matching-signature-found).

Can you try to open an image with `imread(filename)` and send the output of `print(type(image), image.dtype)`?

Also, could you provide the scikit-image version you have installed?

**Comment by EllenvdL** [comment]
The scikit-image version I have installed is 0.21.0. On the computer of someone else Morgana worked and I saw scikit-image 0.19.2 was used. I now downgraded to 0.19.2 on my computer and generating masks works now. Thank you for the fast replies!

**Comment by grinic** [comment]
Great to hear, and thanks for the feedback on the scikit-image version!
