### ISSUE TITLE
pip install scikit-image==0.18 fails

### ISSUE THREAD

**Issue by bennm37** [LabTrivedi/MOrgAna#6]
Following the standard installation instructions 
<code> conda create -n morgana python=3.9 pip
pip install . </code>
fails on M3 Mac running Sonoma due to the requirement 
<code> scikit-image==0.18 </code>
Just running 
<code> pip install scikit-image==0.18 </code>
in a clean environment fails. Relaxing this requirement to 
<code> scikit-image>=0.18 </code>
worked for me.  Are there any breaking changes in scikit-image after version 0.18?

**Comment by grinic** [comment]
Hello, we have made a few changes in the last couple of days, exactly to solve the scikit-image dependency issue.
Could you please try installing morgana again on a fresh environment and let us know if that works well?

**Comment by bennm37** [comment]
Yes that works thanks!
